In [145]:
import pandas as pd
import numpy as np

In [146]:
df1819Clean = pd.read_csv('Data20182019_No0_CleanFinal.csv')
len(df1819Clean)

13727

In [147]:
df1819Clean.head()

,date,time,day,station,code,min_delay,min_gap,bound,line,vehicle
0,2019-01-01,03:03,Tuesday,DUPONT STATION,MUATC,11,16,N,YU,6061
1,2019-01-01,03:08,Tuesday,EGLINTON WEST STATION,EUATC,11,16,S,YU,5656
2,2019-01-01,03:09,Tuesday,DUPONT STATION,EUATC,6,11,N,YU,5381
3,2019-01-01,03:26,Tuesday,ST CLAIR WEST STATION,EUATC,4,9,N,YU,5571
4,2019-01-01,08:04,Tuesday,DAVISVILLE STATION,MUNOA,5,10,S,YU,0

In [148]:
df1819Clean['id'] = df1819Clean.index +1
df1819Clean.dtypes

date         object
time         object
day          object
station      object
code         object
min_delay     int64
min_gap       int64
bound        object
line         object
vehicle       int64
id            int64
dtype: object

In [149]:
len(df1819Clean)

13727

In [150]:
df_Code_Info = pd.read_excel('LookUp_Code_Info.xlsx')
df_Code_Info.head()

    code            code_info
0   EUAC     Air Conditioning
1   EUAL  Alternating Current
2  EUATC   ATC RC&S Equipment
3   EUBK               Brakes
4   EUBO                 Body

In [151]:
temp_info = df_Code_Info.loc[df_Code_Info['code'] == "PUEO"]
len(temp_info)

0

In [152]:
temp_info = df_Code_Info.loc[df_Code_Info['code'] == "PUTDN"]
len(temp_info)

1

In [153]:
temp = df1819Clean.loc[df1819Clean['code'] == "PUEO"]
len(temp)
#MUPF, PUEO, PUEWZ, PUEME

19

In [154]:
temp = df1819Clean.loc[df1819Clean['code'] == "PUEME"]
len(temp)

1

In [155]:
temp = df1819Clean.loc[df1819Clean['code'] == "MUPF"]
len(temp)

5

In [156]:
temp = df1819Clean.loc[df1819Clean['code'] == "PUEME"]
len(temp)

1

In [157]:
temp = df1819Clean.loc[df1819Clean['code'] == "PUTDN"]
len(temp)

32

In [158]:
df_Code_Info_eu = df_Code_Info[df_Code_Info["code"].str.contains('EU')]
#df_Code_Info_eu

In [159]:
df1819Clean_codes = df1819Clean.code.unique()
series1819Clean_codes = pd.Series(df1819Clean_codes)
#series1819Clean_codes.str.contains('EU')

In [160]:
df1819Clean = df1819Clean.merge(df_Code_Info, how="inner", on="code")

In [161]:
df1819Clean.dtypes

date         object
time         object
day          object
station      object
code         object
min_delay     int64
min_gap       int64
bound        object
line         object
vehicle       int64
id            int64
code_info    object
dtype: object

In [162]:
len(df1819Clean)

13694

In [163]:
df1819Clean.head()

,date,time,day,station,code,min_delay,min_gap,bound,line,vehicle,id,code_info
0,2019-01-01,03:03,Tuesday,DUPONT STATION,MUATC,11,16,N,YU,6061,1,ATC Project
1,2019-01-01,16:02,Tuesday,DUPONT STATION,MUATC,6,10,N,YU,6081,16,ATC Project
2,2019-01-07,15:22,Monday,GLENCAIRN STATION,MUATC,5,8,S,YU,6131,103,ATC Project
3,2019-01-10,15:41,Thursday,DUPONT STATION,MUATC,4,7,N,YU,5466,165,ATC Project
4,2019-01-11,02:11,Friday,EGLINTON WEST STATION,MUATC,5,10,N,YU,5806,171,ATC Project

In [164]:
df_Lat_Long = pd.read_excel('LookUp_Lat_Long.xlsx')
df_Lat_Long.head()

                   station   latitude  longitude
0       VAUGHAN MC STATION  43.794167 -79.527500
1      HIGHWAY 407 STATION  43.783889 -79.523056
2  PIONEER VILLAGE STATION  43.776944 -79.509444
3  YORK UNIVERSITY STATION  43.774167 -79.499722
4       FINCH WEST STATION  43.765278 -79.491111

In [165]:
df1819Clean = df1819Clean.merge(df_Lat_Long,on="station")
df1819Clean.head()

,date,time,day,station,code,min_delay,min_gap,bound,line,vehicle,id,code_info,latitude,longitude
0,2019-01-01,03:03,Tuesday,DUPONT STATION,MUATC,11,16,N,YU,6061,1,ATC Project,43.674584,-79.40683
1,2019-01-01,16:02,Tuesday,DUPONT STATION,MUATC,6,10,N,YU,6081,16,ATC Project,43.674584,-79.40683
2,2019-01-10,15:41,Thursday,DUPONT STATION,MUATC,4,7,N,YU,5466,165,ATC Project,43.674584,-79.40683
3,2019-01-14,09:05,Monday,DUPONT STATION,MUATC,5,7,N,YU,5656,230,ATC Project,43.674584,-79.40683
4,2019-01-16,09:00,Wednesday,DUPONT STATION,MUATC,4,6,N,YU,5656,266,ATC Project,43.674584,-79.40683

In [166]:
df1819Clean.dtypes

date          object
time          object
day           object
station       object
code          object
min_delay      int64
min_gap        int64
bound         object
line          object
vehicle        int64
id             int64
code_info     object
latitude     float64
longitude    float64
dtype: object

In [167]:
df_Line_Name = pd.read_excel('LookUp_Line.xlsx')
df_Line_Name.head()

  line                 line_name
0   YU  Yonge University Spadina
1   BD            Bloor Danforth
2  SRT  Scarborough Rail Transit
3  SHP                  Sheppard

In [168]:
df1819Clean = df1819Clean.merge(df_Line_Name,on="line")
df1819Clean.head()

,date,time,day,station,code,min_delay,min_gap,bound,line,vehicle,id,code_info,latitude,longitude,line_name
0,2019-01-01,03:03,Tuesday,DUPONT STATION,MUATC,11,16,N,YU,6061,1,ATC Project,43.674584,-79.40683,Yonge University Spadina
1,2019-01-01,16:02,Tuesday,DUPONT STATION,MUATC,6,10,N,YU,6081,16,ATC Project,43.674584,-79.40683,Yonge University Spadina
2,2019-01-10,15:41,Thursday,DUPONT STATION,MUATC,4,7,N,YU,5466,165,ATC Project,43.674584,-79.40683,Yonge University Spadina
3,2019-01-14,09:05,Monday,DUPONT STATION,MUATC,5,7,N,YU,5656,230,ATC Project,43.674584,-79.40683,Yonge University Spadina
4,2019-01-16,09:00,Wednesday,DUPONT STATION,MUATC,4,6,N,YU,5656,266,ATC Project,43.674584,-79.40683,Yonge University Spadina

In [169]:
import datetime
tempdate = pd.to_datetime(df1819Clean['date'])
df1819Clean['month'] = tempdate.dt.month_name(locale = 'English')
#df1819Clean['month_number'] = pd.DatetimeIndex(df1819Clean['date']).month
df1819Clean['month_number'] = tempdate.dt.month
df1819Clean['year'] = tempdate.dt.year
df1819Clean.head()

,date,time,day,station,code,min_delay,min_gap,bound,line,vehicle,id,code_info,latitude,longitude,line_name,month,month_number,year
0,2019-01-01,03:03,Tuesday,DUPONT STATION,MUATC,11,16,N,YU,6061,1,ATC Project,43.674584,-79.40683,Yonge University Spadina,January,1,2019
1,2019-01-01,16:02,Tuesday,DUPONT STATION,MUATC,6,10,N,YU,6081,16,ATC Project,43.674584,-79.40683,Yonge University Spadina,January,1,2019
2,2019-01-10,15:41,Thursday,DUPONT STATION,MUATC,4,7,N,YU,5466,165,ATC Project,43.674584,-79.40683,Yonge University Spadina,January,1,2019
3,2019-01-14,09:05,Monday,DUPONT STATION,MUATC,5,7,N,YU,5656,230,ATC Project,43.674584,-79.40683,Yonge University Spadina,January,1,2019
4,2019-01-16,09:00,Wednesday,DUPONT STATION,MUATC,4,6,N,YU,5656,266,ATC Project,43.674584,-79.40683,Yonge University Spadina,January,1,2019

In [170]:
#other method
#df1819Clean['year'] = pd.DatetimeIndex(df1819Clean['date']).year

In [171]:
temphour = pd.to_datetime(df1819Clean['time'])
df1819Clean['hour'] = temphour.dt.hour
df1819Clean.head()

,date,time,day,station,code,min_delay,min_gap,bound,line,vehicle,id,code_info,latitude,longitude,line_name,month,month_number,year,hour
0,2019-01-01,03:03,Tuesday,DUPONT STATION,MUATC,11,16,N,YU,6061,1,ATC Project,43.674584,-79.40683,Yonge University Spadina,January,1,2019,3
1,2019-01-01,16:02,Tuesday,DUPONT STATION,MUATC,6,10,N,YU,6081,16,ATC Project,43.674584,-79.40683,Yonge University Spadina,January,1,2019,16
2,2019-01-10,15:41,Thursday,DUPONT STATION,MUATC,4,7,N,YU,5466,165,ATC Project,43.674584,-79.40683,Yonge University Spadina,January,1,2019,15
3,2019-01-14,09:05,Monday,DUPONT STATION,MUATC,5,7,N,YU,5656,230,ATC Project,43.674584,-79.40683,Yonge University Spadina,January,1,2019,9
4,2019-01-16,09:00,Wednesday,DUPONT STATION,MUATC,4,6,N,YU,5656,266,ATC Project,43.674584,-79.40683,Yonge University Spadina,January,1,2019,9

In [172]:
# Create the bins in which Data will be held 
bins = [0, 5, 9, 12, 15, 18, 23]

# Create the names for the four bins
group_names = ["9PM-1:30AM", "5-9AM", "9AM-12PM", "12-3PM", "3-6PM","6-9PM"]

In [173]:
df1819Clean["time_range"] = pd.cut(df1819Clean["hour"], bins, labels=group_names)
df1819Clean.head()

,date,time,day,station,code,min_delay,min_gap,bound,line,vehicle,id,code_info,latitude,longitude,line_name,month,month_number,year,hour,time_range
0,2019-01-01,03:03,Tuesday,DUPONT STATION,MUATC,11,16,N,YU,6061,1,ATC Project,43.674584,-79.40683,Yonge University Spadina,January,1,2019,3,9PM-1:30AM
1,2019-01-01,16:02,Tuesday,DUPONT STATION,MUATC,6,10,N,YU,6081,16,ATC Project,43.674584,-79.40683,Yonge University Spadina,January,1,2019,16,3-6PM
2,2019-01-10,15:41,Thursday,DUPONT STATION,MUATC,4,7,N,YU,5466,165,ATC Project,43.674584,-79.40683,Yonge University Spadina,January,1,2019,15,12-3PM
3,2019-01-14,09:05,Monday,DUPONT STATION,MUATC,5,7,N,YU,5656,230,ATC Project,43.674584,-79.40683,Yonge University Spadina,January,1,2019,9,5-9AM
4,2019-01-16,09:00,Wednesday,DUPONT STATION,MUATC,4,6,N,YU,5656,266,ATC Project,43.674584,-79.40683,Yonge University Spadina,January,1,2019,9,5-9AM

In [174]:
df1819Clean.shape

(13694, 20)

In [175]:
df1819Clean

,date,time,day,station,code,min_delay,min_gap,bound,line,vehicle,id,code_info,latitude,longitude,line_name,month,month_number,year,hour,time_range
0,2019-01-01,03:03,Tuesday,DUPONT STATION,MUATC,11,16,N,YU,6061,1,ATC Project,43.674584,-79.406830,Yonge University Spadina,January,1,2019,3,9PM-1:30AM
1,2019-01-01,16:02,Tuesday,DUPONT STATION,MUATC,6,10,N,YU,6081,16,ATC Project,43.674584,-79.406830,Yonge University Spadina,January,1,2019,16,3-6PM
2,2019-01-10,15:41,Thursday,DUPONT STATION,MUATC,4,7,N,YU,5466,165,ATC Project,43.674584,-79.406830,Yonge University Spadina,January,1,2019,15,12-3PM
3,2019-01-14,09:05,Monday,DUPONT STATION,MUATC,5,7,N,YU,5656,230,ATC Project,43.674584,-79.406830,Yonge University Spadina,January,1,2019,9,5-9AM
4,2019-01-16,09:00,Wednesday,DUPONT STATION,MUATC,4,6,N,YU,5656,266,ATC Project,43.674584,-79.406830,Yonge University Spadina,January,1,2019,9,5-9AM
5,2019-01-19,01:55,Saturday,DUPONT STATION,MUATC,4,9,N,YU,6031,321,ATC Project,43.674584,-79.406830,Yonge University Spadina,January,1,2019,1,9PM-1:30AM
6,2019-01-20,17:44,Sunday,DUPONT STATION,MUATC,9,13,N,YU,6061,347,ATC Project,43.674584,-79.406830,Yonge University Spadina,January,1,2019,17,3-6PM
7,2019-01-25,01:46,Friday,DUPONT STATION,MUATC,5,10,N,YU,5511,479,ATC Project,43.674584,-79.406830,Yonge University Spadina,January,1,2019,1,9PM-1:30AM
8,2019-01-27,10:12,Sunday,DUPONT STATION,MUATC,8,13,N,YU,5486,524,ATC Project,43.674584,-79.406830,Yonge University Spadina,January,1,2019,10,9AM-12PM
9,2019-02-04,06:36,Monday,DUPONT STATION,MUATC,6,10,N,YU,5726,716,ATC Project,43.674584,-79.406830,Yonge University Spadina,February,2,2019,6,5-9AM
10,2019-02-04,06:51,Monday,DUPONT STATION,MUATC,4,6,N,YU,5981,718,ATC Project,43.674584,-79.406830,Yonge University Spadina,February,2,2019,6,5-9AM
11,2019-02-11,06:19,Monday,DUPONT STATION,MUATC,7,0,N,YU,5561,827,ATC Project,43.674584,-79.406830,Yonge University Spadina,February,2,2019,6,5-9AM
12,2019-02-12,06:36,Tuesday,DUPONT STATION,MUATC,5,9,N,YU,6051,842,ATC Project,43.674584,-79.406830,Yonge University Spadina,February,2,2019,6,5-9AM
13,2019-02-17,01:49,Sunday,DUPONT STATION,MUATC,8,13,N,YU,5876,968,ATC Project,43.674584,-79.406830,Yonge University Spadina,February,2,2019,1,9PM-1:30AM
14,2019-02-18,06:46,Monday,DUPONT STATION,MUATC,6,10,N,YU,6051,982,ATC Project,43.674584,-79.406830,Yonge University Spadina,February,2,2019,6,5-9AM
15,2019-02-25,06:58,Monday,DUPONT STATION,MUATC,5,9,N,YU,5586,1091,ATC Project,43.674584,-79.406830,Yonge University Spadina,February,2,2019,6,5-9AM
16,2019-02-25,07:06,Monday,DUPONT STATION,MUATC,5,7,N,YU,5851,1092,ATC Project,43.674584,-79.406830,Yonge University Spadina,February,2,2019,7,5-9AM
17,2019-03-02,06:31,Saturday,DUPONT STATION,MUATC,7,12,N,YU,5636,1227,ATC Project,43.674584,-79.406830,Yonge University Spadina,March,3,2019,6,5-9AM
18,2019-03-14,08:18,Thursday,DUPONT STATION,MUATC,12,14,N,YU,5126,1436,ATC Project,43.674584,-79.406830,Yonge University Spadina,March,3,2019,8,5-9AM
19,2019-03-14,13:14,Thursday,DUPONT STATION,MUATC,4,7,N,YU,6126,1442,ATC Project,43.674584,-79.406830,Yonge University Spadina,March,3,2019,13,12-3PM
20,2019-03-14,16:16,Thursday,DUPONT STATION,MUATC,8,11,N,YU,6126,1447,ATC Project,43.674584,-79.406830,Yonge University Spadina,March,3,2019,16,3-6PM
21,2019-03-15,10:00,Friday,DUPONT STATION,MUATC,13,15,N,YU,6121,1457,ATC Project,43.674584,-79.406830,Yonge University Spadina,March,3,2019,10,9AM-12PM
22,2019-03-15,10:11,Friday,DUPONT STATION,MUATC,3,5,N,YU,5541,1458,ATC Project,43.674584,-79.406830,Yonge University Spadina,March,3,2019,10,9AM-12PM
23,2019-03-18,08:19,Monday,DUPONT STATION,MUATC,4,6,N,YU,5411,1510,ATC Project,43.674584,-79.406830,Yonge University Spadina,March,3,2019,8,5-9AM
24,2019-03-18,08:36,Monday,DUPONT STATION,MUATC,3,5,N,YU,5591,1511,ATC Project,43.674584,-79.406830,Yonge University Spadina,March,3,2019,8,5-9AM
25,2019-03-18,09:30,Monday,DUPONT STATION,MUATC,4,6,N,YU,5846,1515,ATC Project,43.674584,-79.406830,Yonge University Spadina,March,3,2019,9,5-9AM
26,2019-04-01,06:44,Monday,DUPONT STATION,MUATC,9,12,N,YU,5456,1715,ATC Project,43.674584,-79.406830,Yonge University Spadina,April,4,2019,6,5-9AM
27,2019-04-01,06:53,Monday,DUPONT STATION,MUATC,3,6,N,YU,5676,1716,ATC Project,43.674584,-79.406830,Yonge University Spadina,April,4,2019,6,5-9AM
28,2019-04-01,08:55,Monday,DUPONT STATION,MUATC,3,5,N,YU,5581,1720,ATC Project,43.674584,-79.406830,Yonge University Spadina,April,4,2019,8,5-9AM
29,2019-04-01,09:28,Monday,DUPONT STATION,MUATC,3,5,N,YU,5616,1721,ATC Project,43.674584,-79.406830,Yonge University Spadina,April,4,2019,9,5-9AM
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13664,2018-03-07,16:52,Wednesday,LAWRENCE EAST STATION,SRO,3,8,N,SRT,3015,8018,Passenger Other,43.750278,-79.270278,Scarborough Rail Transit,March,3,2018,16,3-6PM
13665,2018-07-27,00:49,Friday,LAWRENCE EAST STATION,SRO,5,10,N,SRT,3015,10799,Passenger Other,43.750278,-79.270278,Scarborough Rail Transit,July,7,2018,0,NaN
13666,2018-10-05,17:55,Friday,LAWRENCE EAST STATION,SRO,25,30,S,SRT,3022,12210,Passenger Other,43.750278,-79.270278,Scarborough Rail Transit,October,10,2018,17,3-6PM
13667,2019-07-05,16:05,Friday,LAWRENCE EAST STATION,MRD,6,11,E,SRT,3008,3565,Door Problems - Passenger Related,43.750278,-79.270278,Scarborough Rail Transit,July,7,2019,16,3-6PM
13668,2019-02-21,19:29,Thursday,LAWRENCE EAST STATION,SRDP,11,16,N,SRT,3003,1039,Disorderly Patron,43.750278,-79.270278,Scarborough Rail Transit,February,2,2019,19,6-9PM
13669,2019-02-21,19:29,Thursday,LAWRENCE EAST STATION,SRDP,11,16,N,SRT,3003,1040,Disorderly Patron,43.750278,-79.270278,Scarborough Rail Transit,February,2,2019,19,6-9PM
13670,2019-12-23,11:17,Monday,LAWRENCE EAST STATION,SRDP,3,9,S,SRT,3014,6537,Disorderly Patron,43.750278,-79.270278,Scarborough Rail Transit,December,12,2019,11,9AM-12PM
13671,2018-11-15,18:50,Thursday,LAWRENCE EAST STATION,SRDP,3,9,N,SRT,3017,12944,Disorderly Patron,43.750278,-79.270278,Scarborough Rail Transit,November,11,2018,18,3-6PM
13672,2019-03-01,15:32,Friday,LAWRENCE EAST STATION,SRAP,21,26,S,SRT,3020,1209,Assault / Patron Involved,43.750278,-79.270278,Scarborough Rail Transit,March,3,2019,15,12-3PM
13673,2019-08-19,15:17,Monday,LAWRENCE EAST STATION,SRAP,16,21,S,SRT,3024,4383,Assault / Patron Involved,43.750278,-79.270278,Scarborough Rail Transit,August,8,2019,15,12-3PM
13674,2018-05-03,20:45,Thursday,LAWRENCE EAST STATION,SRAP,20,25,N,SRT,3000,8997,Assault / Patron Involved,43.750278,-79.270278,Scarborough Rail Transit,May,5,2018,20,6-9PM
13675,2019-05-13,10:35,Monday,LAWRENCE EAST STATION,SRUT,5,10,S,SRT,3007,2512,Unauthorized at Track Level,43.750278,-79.270278,Scarborough Rail Transit,May,5,2019,10,9AM-12PM
13676,2019-08-11,15:30,Sunday,LAWRENCE EAST STATION,ERPR,5,11,N,SRT,3017,4228,Propulsion System,43.750278,-79.270278,Scarborough Rail Transit,August,8,2019,15,12-3PM
13677,2018-02-23,06:41,Friday,LAWRENCE EAST STATION,ERPR,12,17,N,SRT,3007,7797,Propulsion System,43.750278,-79.270278,Scarborough Rail Transit,February,2,2018,6,5-9AM
13678,2019-04-14,23:14,Sunday,LAWRENCE EAST STATION,ERNT,3,9,N,SRT,3021,1960,Equipment - No Trouble Found,43.750278,-79.270278,Scarborough Rail Transit,April,4,2019,23,6-9PM
13679,2019-07-06,21:54,Saturday,LAWRENCE EAST STATION,ERNT,5,11,E,SRT,3021,3589,Equipment - No Trouble Found,43.750278,-79.270278,Scarborough Rail Transit,July,7,2019,21,6-9PM
13680,2018-07-04,20:34,Wednesday,LAWRENCE EAST STATION,ERNT,6,11,N,SRT,3023,10262,Equipment - No Trouble Found,43.750278,-79.270278,Scarborough Rail Transit,July,7,2018,20,6-9PM
13681,2018-08-08,05:59,Wednesday,LAWRENCE EAST STATION,ERWA,9,15,S,SRT,3026,11062,Warning Alarm Systems,43.750278,-79.270278,Scarborough Rail Transit,August,8,2018,5,9PM-1:30AM
13682,2018-08-21,13:42,Tuesday,LAWRENCE EAST STATION,ERWA,4,9,N,SRT,3011,11337,Warning Alarm Systems,43.750278,-79.270278,Scarborough Rail Transit,August,8,2018,13,12-3PM
13683,2019-07-10,07:28,Wednesday,LAWRENCE EAST STATION,MRPAA,3,8,S,SRT,3027,3656,Passenger Assistance Alarm Activated - No Trou...,43.750278,-79.270278,Scarborough Rail Transit,July,7,2019,7,5-9AM
13684,2019-07-18,17:36,Thursday,LAWRENCE EAST STATION,MRPAA,3,8,N,SRT,3025,3811,Passenger Assistance Alarm Activated - No Trou...,43.750278,-79.270278,Scarborough Rail Transit,July,7,2019,17,3-6PM
13685,2018-06-15,13:55,Friday,LAWRENCE EAST STATION,ERTL,71,77,S,SRT,3026,9844,Trainline System,43.750278,-79.270278,Scarborough Rail Transit,June,6,2018,13,12-3PM
13686,2018-10-17,06:46,Wednesday,LAWRENCE EAST STATION,ERTL,3,8,S,SRT,3018,12395,Trainline System,43.750278,-79.270278,Scarborough Rail Transit,October,10,2018,6,5-9AM
13687,2019-07-05,07:54,Friday,LAWRENCE EAST STATION,MRUI,5,10,S,SRT,3002,3556,Injured or ill Customer (On Train) - Transported,43.750278,-79.270278,Scarborough Rail Transit,July,7,2019,7,5-9AM
13688,2018-06-06,08:14,Wednesday,LAWRENCE EAST STATION,MRUI,7,12,S,SRT,3020,9649,Injured or ill Customer (On Train) - Transported,43.750278,-79.270278,Scarborough Rail Transit,June,6,2018,8,5-9AM
13689,2018-09-14,08:54,Friday,LAWRENCE EAST STATION,MRUI,6,11,S,SRT,3022,11806,Injured or ill Customer (On Train) - Transported,43.750278,-79.270278,Scarborough Rail Transit,September,9,2018,8,5-9AM
13690,2019-05-23,21:44,Thursday,LAWRENCE EAST STATION,ERLT,8,15,N,SRT,3019,2736,Lighting System,43.750278,-79.270278,Scarborough Rail Transit,May,5,2019,21,6-9PM
13691,2019-06-06,01:00,Thursday,LAWRENCE EAST STATION,SRCOL,19,24,S,SRT,3024,3000,Collector Booth Alarm Activated,43.750278,-79.270278,Scarborough Rail Transit,June,6,2019,1,9PM-1:30AM
13692,2018-05-18,15:25,Friday,LAWRENCE EAST STATION,SREAS,9,13,S,SRT,3026,9307,Emergency Alarm Station Activation,43.750278,-79.270278,Scarborough Rail Transit,May,5,2018,15,12-3PM
13693,2018-06-26,01:03,Tuesday,LAWRENCE EAST STATION,SREAS,18,24,N,SRT,3015,10081,Emergency Alarm Station Activation,43.750278,-79.270278,Scarborough Rail Transit,June,6,2018,1,9PM-1:30AM

In [176]:
df1819Clean.sort_values('id', inplace = True, ascending=True)
df1819Clean.columns()

TypeError: 'Index' object is not callable

In [177]:
df1819Final = df1819Clean[['id', 'date', 'time', 'day', 'station', 'code', 'min_delay', 'min_gap',
       'bound', 'line', 'vehicle', 'code_info', 'latitude', 'longitude',
       'line_name', 'month', 'time_range', 'month_number', 'hour', 'year']]
df1819Final.head()

,id,date,time,day,station,code,min_delay,min_gap,bound,line,vehicle,code_info,latitude,longitude,line_name,month,time_range,month_number,hour,year
0,1,2019-01-01,03:03,Tuesday,DUPONT STATION,MUATC,11,16,N,YU,6061,ATC Project,43.674584,-79.406830,Yonge University Spadina,January,9PM-1:30AM,1,3,2019
269,2,2019-01-01,03:08,Tuesday,EGLINTON WEST STATION,EUATC,11,16,S,YU,5656,ATC RC&S Equipment,43.699209,-79.435819,Yonge University Spadina,January,9PM-1:30AM,1,3,2019
53,3,2019-01-01,03:09,Tuesday,DUPONT STATION,EUATC,6,11,N,YU,5381,ATC RC&S Equipment,43.674584,-79.406830,Yonge University Spadina,January,9PM-1:30AM,1,3,2019
1035,4,2019-01-01,03:26,Tuesday,ST CLAIR WEST STATION,EUATC,4,9,N,YU,5571,ATC RC&S Equipment,43.683888,-79.415113,Yonge University Spadina,January,9PM-1:30AM,1,3,2019
5765,5,2019-01-01,08:04,Tuesday,DAVISVILLE STATION,MUNOA,5,10,S,YU,0,No Operator Immediately Available - Not E.S.A....,43.697778,-79.397222,Yonge University Spadina,January,5-9AM,1,8,2019

In [178]:
df1819Final.to_csv('ttc_subway_delay_2018_2019_from_pandas.csv', index=False)

In [179]:
len(df1819Final)

13694

In [180]:
df1819Final.nunique()

id              13694
date              730
time             1279
day                 7
station            80
code              177
min_delay         114
min_gap           125
bound               5
line                4
vehicle           636
code_info         134
latitude           74
longitude          76
line_name           4
month              12
time_range          6
month_number       12
hour               24
year                2
dtype: int64