In [1]:
import pandas as pd
import numpy as np

In [21]:
df1819 = pd.read_csv('ttc_subway_delay_2018_2019.csv')
len(df1819)

13727

In [22]:
df1819.dtypes

id                int64
date             object
time             object
day              object
station          object
code             object
min_delay         int64
min_gap           int64
bound            object
line             object
vehicle           int64
code_info        object
latitude        float64
longitude       float64
line_name        object
month            object
time_range       object
month_number      int64
hour              int64
year              int64
dtype: object

In [23]:
df1819.head()

,id,date,time,day,station,code,min_delay,min_gap,bound,line,vehicle,code_info,latitude,longitude,line_name,month,time_range,month_number,hour,year
0,1,2019-01-01,3:03,Tuesday,DUPONT STATION,MUATC,11,16,N,YU,6061,ATC Project,43.674584,-79.406830,Yonge University Spadina,January,9PM-1:30AM,1,3,2019
1,2,2019-01-01,3:08,Tuesday,EGLINTON WEST STATION,EUATC,11,16,S,YU,5656,ATC RC&S Equipment,43.699209,-79.435819,Yonge University Spadina,January,9PM-1:30AM,1,3,2019
2,3,2019-01-01,3:09,Tuesday,DUPONT STATION,EUATC,6,11,N,YU,5381,ATC RC&S Equipment,43.674584,-79.406830,Yonge University Spadina,January,9PM-1:30AM,1,3,2019
3,4,2019-01-01,3:26,Tuesday,ST CLAIR WEST STATION,EUATC,4,9,N,YU,5571,ATC RC&S Equipment,43.683888,-79.415113,Yonge University Spadina,January,9PM-1:30AM,1,3,2019
4,5,2019-01-01,8:04,Tuesday,DAVISVILLE STATION,MUNOA,5,10,S,YU,0,No Operator Immediately Available - Not E.S.A....,43.697778,-79.397222,Yonge University Spadina,January,5-9AM,1,8,2019

In [25]:
dfstation = pd.read_excel('station_sort.xlsx')
dfstation

    Unnamed: 0                     station                          Sort
0            0          VAUGHAN MC STATION           0VAUGHAN MC STATION
1            1         HIGHWAY 407 STATION          1HIGHWAY 407 STATION
2            2      PIONEER VILLAGE STATIO       2PIONEER VILLAGE STATIO
3            3      YORK UNIVERSITY STATIO       3YORK UNIVERSITY STATIO
4            4          FINCH WEST STATION           4FINCH WEST STATION
5            5      DOWNSVIEW PARK STATION       5DOWNSVIEW PARK STATION
6            6       SHEPPARD WEST STATION        6SHEPPARD WEST STATION
7            7              WILSON STATION               7WILSON STATION
8            8            YORKDALE STATION             8YORKDALE STATION
9            9       LAWRENCE WEST STATION        9LAWRENCE WEST STATION
10          10           GLENCAIRN STATION           10GLENCAIRN STATION
11          11       EGLINTON WEST STATION       11EGLINTON WEST STATION
12          12       ST CLAIR WEST STATION       12ST CLAIR WEST STATION
13          13              DUPONT STATION              13DUPONT STATION
14          14         SPADINA YUS STATION         14SPADINA YUS STATION
15          15       ST GEORGE YUS STATION       15ST GEORGE YUS STATION
16          16              MUSEUM STATION              16MUSEUM STATION
17          17        QUEEN'S PARK STATION        17QUEEN'S PARK STATION
18          18          ST PATRICK STATION          18ST PATRICK STATION
19          19             OSGOODE STATION             19OSGOODE STATION
20          20           ST ANDREW STATION           20ST ANDREW STATION
21          21               UNION STATION               21UNION STATION
22          22                KING STATION                22KING STATION
23          23               QUEEN STATION               23QUEEN STATION
24          24              DUNDAS STATION              24DUNDAS STATION
25          25             COLLEGE STATION             25COLLEGE STATION
26          26           WELLESLEY STATION           26WELLESLEY STATION
27          27     YONGE BLOOR YUS STATION     27YONGE BLOOR YUS STATION
28          28            ROSEDALE STATION            28ROSEDALE STATION
29          29          SUMMERHILL STATION          29SUMMERHILL STATION
..         ...                         ...                           ...
50          50            CHRISTIE STATION            50CHRISTIE STATION
51          51            BATHURST STATION            51BATHURST STATION
52          52          SPADINA BD STATION          52SPADINA BD STATION
53          53        ST GEORGE BD STATION        53ST GEORGE BD STATION
54          54                 BAY STATION                 54BAY STATION
55          55      YONGE BLOOR BD STATION      55YONGE BLOOR BD STATION
56          56          SHERBOURNE STATION          56SHERBOURNE STATION
57          57        CASTLE FRANK STATION        57CASTLE FRANK STATION
58          58           BROADVIEW STATION           58BROADVIEW STATION
59          59             CHESTER STATION             59CHESTER STATION
60          60                PAPE STATION                60PAPE STATION
61          61            DONLANDS STATION            61DONLANDS STATION
62          62           GREENWOOD STATION           62GREENWOOD STATION
63          63             COXWELL STATION             63COXWELL STATION
64          64            WOODBINE STATION            64WOODBINE STATION
65          65         MAIN STREET STATION         65MAIN STREET STATION
66          66       VICTORIA PARK STATION       66VICTORIA PARK STATION
67          67              WARDEN STATION              67WARDEN STATION
68          68          KENNEDY BD STATION          68KENNEDY BD STATION
69          69         KENNEDY SRT STATION         69KENNEDY SRT STATION
70          70       LAWRENCE EAST STATION       70LAWRENCE EAST STATION
71          71           ELLESMERE STATION           71ELLESMERE STATION
72          72             MIDLAND STATION             72MIDLAND STATION
73          73      SCARBOROUGH CTR STATIO      73SCARBOROUGH CTR STATIO
74          74             MCCOWAN STATION             74MCCOWAN STATION
75          75  SHEPPARD-YONGE SHP STATION  75SHEPPARD-YONGE SHP STATION
76          76             BAYVIEW STATION             76BAYVIEW STATION
77          77           BESSARION STATION           77BESSARION STATION
78          78              LESLIE STATION              78LESLIE STATION
79          79           DON MILLS STATION           79DON MILLS STATION

[80 rows x 3 columns]

In [26]:
df18 = df1819.loc[(df1819['year'] == 2018)]
len(df18)

7049

In [27]:
FailingDrugs = []

In [ ]:
for x in range(5):

In [15]:
df19 = df1819.loc[(df1819['year'] == 2019)]
len(df19)

6678

In [17]:
grouped_df18 = df18.groupby("station")
average18 = grouped_df18["min_delay"].mean()
amount18 = grouped_df18["min_delay"].count()

In [20]:
grouped_df19 = df19.groupby("station")
average19 = grouped_df19["min_delay"].mean()
amount19 = grouped_df19["min_delay"].count()